name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api, base, config, database, file, navigation, shared, template, user]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build ${{ matrix.package }}
        run: pnpm --filter @mixcore/${{ matrix.package }} build
      - name: Run tests for ${{ matrix.package }}
        run: pnpm --filter @mixcore/${{ matrix.package }} test
